const professionals = [
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 1,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    userId: 2,
    profession: [
      {
        id: 2,
        name: "carpintero",
        ClientNeedId: null,
        Profession_Professional: {
          ProfessionalId: 2,
          ProfessionId: 2,
        },
      },
    ],
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 3,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 4,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 5,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 6,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 7,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 8,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 9,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 10,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 11,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 12,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 13,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 14,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 15,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 16,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 17,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 18,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 19,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 20,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 21,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 22,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 23,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 24,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 25,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 26,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 27,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 28,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 29,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 30,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 31,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 32,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 33,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 34,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 35,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 36,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 37,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 38,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 39,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 40,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 41,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 42,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 43,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 44,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 45,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 46,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 47,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 48,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 49,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 50,
  },
];

const professionalMap = professionals.map((el) => {
  return {
    certification_name: el.certification_name,
    certification_img: el.certification_img,
    status: el.status,
    UserId: el.userId,
  };
});

module.exports = { professionalMap };
