const offers = [
  {
    description: "Destapar cañería",
    price: 300,
    duration: 60,
    materials: false,
    guarantee_time: 30,
    UserId: 1,
    ClientNeedId: 1,
  },
  {
    description: "Destapar cañería",
    price: 300,
    duration: 60,
    materials: false,
    guarantee_time: 30,
    UserId: 1,
    ClientNeedId: 15,
  },
  {
    description: "Destapar cañería",
    price: 300,
    duration: 60,
    materials: false,
    guarantee_time: 30,
    UserId: 4,
    ClientNeedId: 2,
  },
  {
    description: "Destapar cañería",
    price: 300,
    duration: 60,
    materials: false,
    guarantee_time: 30,
    UserId: 4,
    ClientNeedId: 3,
  },
  {
    description: "Cambiar llave de agua",
    price: 150,
    duration: 30,
    materials: true,
    guarantee_time: 30,
    UserId: 5,
    ClientNeedId: 4,
  },
  {
    description: "Cortado y lijado de tablas",
    price: 40,
    duration: 40,
    materials: true,
    guarantee_time: 30,
    UserId: 2,
    ClientNeedId: 5,
  },
  {
    description: "Barnizado a tablas (precio por pieza)",
    price: 50,
    duration: 120,
    materials: true,
    guarantee_time: 30,
    UserId: 2,
    ClientNeedId: 6,
  },
  {
    description: "Armado de zapatas para colado",
    price: 80,
    duration: 30,
    materials: false,
    guarantee_time: 0,
    UserId: 3,
    ClientNeedId: 7,
  },
  {
    description: "Colado de losa precio por m3",
    price: 250,
    duration: 00,
    materials: false,
    guarantee_time: 0,
    UserId: 3,
    ClientNeedId: 10,
  },
  {
    description: "Colado de losa precio por m3",
    price: 250,
    duration: 00,
    materials: false,
    guarantee_time: 0,
    UserId: 5,
    ClientNeedId: 8,
  },
  {
    description: "Colado de losa precio por m3",
    price: 250,
    duration: 00,
    materials: false,
    guarantee_time: 0,
    UserId: 10,
    ClientNeedId: 7,
  },
  {
    description: "Colado de losa precio por m3",
    price: 250,
    duration: 00,
    materials: false,
    guarantee_time: 0,
    UserId: 45,
    ClientNeedId: 2,
  },
];

const offerMap = offers.map((el) => {
  return {
    description: el.description,
    price: el.price,
    duration: el.duration,
    materials: el.materials,
    guarantee_time: el.guarantee_time,
    UserId: el.UserId,
    ClientNeedId: el.ClientNeedId,
  };
});

module.exports = { offerMap };
